# Generated by Django 2.0.1 on 2018-02-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_car_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='car_model',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='user_model',
            new_name='user',
        ),
    ]
