# Generated by Django 2.0.1 on 2018-02-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180216_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='stop',
            field=models.DateField(null=True),
        ),
    ]
